version: "3.8"

services:
  app:
    build: .
    container_name: laravel-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=https://admin-team5-jkg2alhnyjo60.sel4.cloudtype.app/
      - DB_PORT=30289
      - DB_DATABASE=team5
      - DB_USERNAME=root
      - DB_PASSWORD=team51234

  db:
    image: mariadb:latest
    container_name: laravel-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=team51234
      - MYSQL_DATABASE=team5
      - MYSQL_USER=root
      - MYSQL_PASSWORD=team51234
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
