version: "3.8"

services:
  app:
    build: .
    container_name: laravel-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_name
      - DB_USERNAME=root
      - DB_PASSWORD=password

  db:
    image: mariadb:latest
    container_name: laravel-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
