version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: laravel_mariadb
    environment:
      MYSQL_DATABASE: team5
      MYSQL_ROOT_PASSWORD: team51234
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  volumes:
    mariadb_data: DB_CONNECTION=mysql
      DB_HOST=root
      DB_PORT=30289
